# Generated by Django 5.2.15 on 2026-06-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100, unique=True)),
                ('productive_status', models.BooleanField(default=False)),
                ('category', models.CharField(default='Uncategorized', max_length=100)),
                ('display_color', models.CharField(default='#6E7681', max_length=20)),
                ('is_auto_registered', models.BooleanField(default=False, help_text='True if this row was created automatically because the activity appeared in data but had no existing configuration.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['activity_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_name', models.CharField(max_length=150, unique=True)),
                ('configuration_value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['configuration_name'],
            },
        ),
    ]
