# Generated by Django 5.2.15 on 2026-06-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('default', 'Default bundled dataset'), ('upload', 'User upload')], default='upload', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('invalid_records', models.IntegerField(default=0)),
                ('duplicates_removed', models.IntegerField(default=0)),
                ('missing_values_handled', models.IntegerField(default=0)),
                ('duration_mismatches_fixed', models.IntegerField(default=0)),
                ('final_clean_records', models.IntegerField(default=0)),
                ('zero_hour_count', models.IntegerField(default=0)),
                ('negative_hour_count', models.IntegerField(default=0)),
                ('outlier_hour_count', models.IntegerField(default=0)),
                ('details_json', models.TextField(blank=True, default='[]')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='shifts.dataset')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.FloatField()),
                ('activity_reason', models.CharField(max_length=150)),
                ('duration_was_recalculated', models.BooleanField(default=False, help_text="True if the original HOURS value didn't match END-START and was recalculated during cleaning.")),
                ('source_row_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_records', to='config_app.activityconfiguration')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_records', to='shifts.dataset')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'start_time'], name='shifts_shif_date_930b66_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'source_row_hash'), name='unique_row_per_dataset')],
            },
        ),
    ]
